services:
  # redis:
  #   image: redis:latest
  #   restart: always
  #   command: ["redis-server", "--bind", "redis", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}"]
  #   environment:
  #     - REDIS_PASSWORD=$REDIS_PASSWORD
  #   ports:
  #     - '6379:6379'
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #     interval: 30s
  #     timeout: 20s
  #     retries: 5
  #     start_period: 5s
  # mysqldb:
  #   image: mysql:5.7
  #   restart: unless-stopped
  #   env_file: ./.lukoil.env
  #   command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
  #   environment:
  #     - MYSQL_ROOT_HOST=%
  #     - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
  #     - MYSQL_DATABASE=$DB_NAME
  #   volumes:
  #     - db:/var/lib/mysql
  #   ports:
  #   - 3307:3306
  app:
    # depends_on:
    #   - mysqldb
    build:
      context: .
      target: builder
    command: sh -c -f "yarn mikro-orm schema:update --run&&yarn mikro-orm seeder:run --class=ConfigSeeder;yarn run start:prod"
    restart: unless-stopped
    env_file: ./.lukoil.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src/:/app/src/
      - static:/app/dist/public/files
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
volumes: 
    db:
    static: